### PR TITLE
Add STUD/HighlightType

### PR DESCRIPTION
**Pull request by ZingBallyhoo**
Adds HighlightType STUD.

ListHighlightType probably isn't that useful, but it's probably a good idea to include it anyway.

### CODE REVIEW

**Comment by naomichan** [comment]
I don't know the full effects in terms of memory in the case of implementing every STUD

**Comment by ZingBallyhoo** [comment]
@naomichan Right, currently uses ~420MB of ram when using ListHighlightType. Are there any STUD types that are important to implement but haven't been done yet, I'm currently just doing whatever is named on the wiki. I don't want to clog up OWLib (and eventually STULib) with a bunch of types that nobody cares about.

**Comment by naomichan** [comment]
My major concern are STU types that are in 003 and 01B files as they can get quite large.

However, memory usage in general _should be_ lower when [rewrite/stu](https://github.com/overtools/OWLib/tree/rewrite/stu) is finished.

**Comment by naomichan** [comment]
Ideally we want to implement _all_ STU types, but if the memory issue gets out of hand we'll probably start to load them in as they're requested.

**Pull request merged**
