### PR TITLE
Add STUD/Subtitle

### PR DESCRIPTION
**Pull request by ZingBallyhoo**
I'm not sure what's happening with the array, it doesn't seem to work in the same way as others, it uses uints throughout. I'm probably doing something wrong.

The actual data is in instance 2 of the 071 files, I'm not sure what instance 1 is used for.

### CODE REVIEW

**Comment by ZingBallyhoo** [comment]
(writing while falling asleep, I'm probably forgetting things)

I think that unk1 is the offset to the array def. Data starts at 112, and I remember that the definition was one line above the data (16 bytes per line in Hexedit), which makes 96. Still wouldn't work with standard array thingy anyway? (because of unk7 is between the count and offset, and it's a weird number.)

**Comment by naomichan** [comment]
If I recall correctly, the syntax is similar to EncryptionKey.

You **_really need to stop including stuff from pointers in the header_**

**Comment by ZingBallyhoo** [comment]
Better now? unk1 was the array definition offset as sleepy me said.

**Comment by Js41637** [comment]
Does this just list the subtitles? I know subtitles are only used for Uprising at the moment but was there anyway to like a subtitle to the sound file it's for?

**Comment by ZingBallyhoo** [comment]
@Js41637 Currently only the subtitle string, I don't yet know how the sound and the text are linked. It might have something to do with instance 1. I'll take a look.

**Comment by naomichan** [comment]
It's not instance 1. The STU file itself is linked with the sound file in one of the other sound STUs.

I've got the data cataloged, I'm just waiting for 1.14 before I start implementing cross-STU logic since it involves 3 different STU instances.

**Comment by ZingBallyhoo** [comment]
@naomichan I see.

**Pull request merged**
