### PR TITLE
Reimplementing STUs for 1.14 [WIP]

### PR DESCRIPTION
**Pull request by ZingBallyhoo**
TODO:

* [ ] STUAchievement doesn't always work.
 * Most of the time Unknown1 is a int, sometimes its a long.
   * I might be missing a field
* [ ] STUAnnouncerVoiceList [primary](https://github.com/overtools/OWLib/blob/master/OWLib/Types/STUD/AnnouncerVoiceList.cs#L44) and [secondary](https://github.com/overtools/OWLib/blob/master/OWLib/Types/STUD/AnnouncerVoiceList.cs#L45), I can't figure out how it works now.
* [ ] More types
* [ ] 1.13 support
* [ ] Names for UnknownStringA and B in STUAchievement 
* [ ] Re-do all ids.

Current added things:
* STUSubtitle
* STULootbox
* STUHighlightType
* STUBrawlName
* STUAchievement
* STUAnnouncerVoiceList
* STUDebug now supports a wildcard for path, for easy testing new types.
* STUEncryptionKey
* DumpKey is now ListKey and the option has changed from "keys" to "list-keys"

### CODE REVIEW

**Comment by naomichan** [comment]
> Most of the time Unknown1 is a int, sometimes its a long.

I'm probably going to be fixing this later by reading the buffer size provided by the field in the STU and then casting it to the appropriate size (most likely it'll only go up so in this case Unknown1 would be defined as a long.)

**Comment by ZingBallyhoo** [comment]
@naomichan I just realized something. Sometimes it exists, sometimes it doesn't. If it is doesn't exist then long or not defining it works, otherwise int.

**Comment by naomichan** [comment]
For now I'd ask you to stop implementing new STUs until it goes live. I fear they might just refresh the STU fields for every update.

**Comment by ZingBallyhoo** [comment]
@naomichan Yeah, I've stopped for now. I really don't fancy re-doing everything every patch. It isn't going to be 'smaller patch sizes' if they keep re-rolling all of the ids like this.

**Comment by naomichan** [comment]
Afaik they only removed files and remapped the fields/instances, so it's pretty much going to be 1.1 GB patches every single time if they keep this up

**Comment by ZingBallyhoo** [comment]
@naomichan I'm pretty sure that is what happened, [here](https://gist.githubusercontent.com/ZingBallyhoo/4973ac8a0e709dcae370bafd27bd7b20/raw/a92db45e43ce153f6c6ddacbc157180c15b251cc/ow_diff_39241) is a 66,700 item list of changed files in 39341, all of the STU types seem to be in there.

**Comment by naomichan** [comment]
In the future work directly on the overwatch/1.14 branch.

**Comment by ZingBallyhoo** [comment]
@naomichan Right, will do.

**Pull request merged**
