### PR TITLE
List OWL unlocks separately to Other Unlocks

### PR DESCRIPTION
**Pull request by Js41637**

### CODE REVIEW

**Comment by ZingBallyhoo** [comment]
¯\\\_(ツ)\_/¯

Don't really know how to handle this properly

**Comment by Js41637** [comment]
Handle wot

**Comment by ZingBallyhoo** [comment]
Displaying how the data actually is in the client is vs how we think that the data should be represented.

**Comment by Js41637** [comment]
Is only a list, don't think it really matters. I think it should try and
show as much information as possible while keeping it simple, I think
separating them makes sense, I don't think it really matters to anyone how
it is actually classified ingame.

**Pull request merged**
