### PR TITLE
Various stuff...

### PR DESCRIPTION
**Pull request by prophetl33t**
Fix TankLibHelper outputing floats in wrong fomat  (comma instead of dot, depends on culture set on system)
If extract folder for TLH doesn't exist - create one
Workshop enum?????????????????????????????????????????
Fixed output of json data to the file (with > operator(not through --json))
List-everything
.cs file name now matches class name

### CODE REVIEW

**Comment by Js41637** [comment]
The json thing is intentional. If you use the pipe operator it will include normal logs therefore it won't be valid json. 

Also why do we need a list everything?

**Comment by prophetl33t** [comment]
I needed list-everything because i use data from different list commands and it was easier to create a thing that dumps all data. Also there is extract-everything, why not? Json change was made because list-everything > EVERYTHING.txt didn't work properly. I can remove it if it's problematic.

**Comment by Js41637** [comment]
Well even if we did add a mode just cause one person wanted to use it. It doesn't even work properly like other modes. What you need to do is pass the flags to every command and manually set a file name for each so it can save each as a valid json file. Though not all modes support it as far as I know. 

Also a mode like this should be sensitive cause it doesn't really work properly and it'll just clog the already very cluttered help.

**Comment by Js41637** [comment]
I mean you can add the mode. I would just like it to work _properly_. It's possible because we already have a mode like this on our internal versions of the tools.

**Comment by prophetl33t** [comment]
No :) 
I mean.. It works for me, easier to remove it from PR.

**Pull request closed without merging**
