### PR TITLE
smol tweaks

### PR DESCRIPTION
**Pull request by prophetl33t**
OutputJSON now can output to console
A bit better description for workshop stuff
0.0001% more memes

### CODE REVIEW

**Comment by Js41637** [comment]
JSON already outputs to the console if you don't give it an output directory? What is the benefit of doing this?

**Comment by prophetl33t** [comment]
Made some commands output json in console without --json flag and reverted OutputJSON changes in 55407824c0e086968b61231f049034b48db8b6b8

**Comment by Js41637** [comment]
looks ok i guess, can u please undo the changes you made to the json file, brackets on new lines are for losers, sorry, i don't make the rules.

**Comment by prophetl33t** [comment]
done

**Comment by Js41637** [comment]
thanks

**Pull request merged**
